"""empty message

Revision ID: 460671b5dfa4
Revises: 248f0cd0ecad
Create Date: 2024-04-02 14:14:00.130534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "460671b5dfa4"
down_revision: Union[str, None] = "248f0cd0ecad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("follow_book_id_key", "follow", type_="unique")
    op.drop_constraint("follow_user_id_key", "follow", type_="unique")
    op.drop_constraint(
        "read_history_book_id_key", "read_history", type_="unique"
    )
    op.drop_constraint(
        "read_history_user_id_key", "read_history", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "read_history_user_id_key", "read_history", ["user_id"]
    )
    op.create_unique_constraint(
        "read_history_book_id_key", "read_history", ["book_id"]
    )
    op.create_unique_constraint("follow_user_id_key", "follow", ["user_id"])
    op.create_unique_constraint("follow_book_id_key", "follow", ["book_id"])
    # ### end Alembic commands ###
